# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=38)),
                ('alias', models.CharField(max_length=38)),
                ('email', models.CharField(max_length=38)),
                ('password', models.CharField(max_length=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_exam_app.User'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='favq',
            field=models.ManyToManyField(related_name='favquotes', to='python_exam_app.User'),
        ),
    ]
