# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0002_auto_20170602_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
