# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0003_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_author',
            field=models.CharField(max_length=38, null=True),
        ),
    ]
